Adding support for slstress into Dockerfile and docker-entrypoint.sh.
sjug/centos-stress pull request #1
Opened 2016-09-27 09:39 UTC by jmencak

Also some minor modifications to jmeter sections.

Signed-off-by: Jiri Mencak <jmencak@redhat.com>

2016-09-27 12:21 UTC, sjug commented
Hey Jiri, I'll give this a test today. As a style note I typically try to follow the [Google shell style guide](https://google.github.io/styleguide/shell.xml).

2016-09-28 12:21 UTC, jmencak commented
Which deviations from the "Google shell style guide" do you see?  I can see a few in the original script too.

2016-09-28 12:24 UTC, sjug commented
@jmencak Mostly the points I addressed int the code review comments. What issues did you see with mine, let me know so I can fix it.

2016-09-28 12:30 UTC, sjug requested changes
See comments inline

2016-09-28 12:30 UTC, sjug commented on Dockerfile
> +RUN curl -Ls https://raw.githubusercontent.com/jmencak/perf-tools/master/slstress_go/logger.sh > \
I like to stack small/related RUN commands so that the Docker image doesn't have too many layers. I think it might be cleaner to change the workdir, set a -O flag, download both files, then stack the chmod.

2016-09-28 12:30 UTC, sjug commented on docker-entrypoint.sh
> +gateway=$(printf "%d.%d.%d.%d" 0x${gw_hex:6:2} 0x${gw_hex:4:2} 0x${gw_hex:2:2} 0x${gw_hex:0:2})
This is ugly, busybox?

2016-09-28 12:30 UTC, sjug commented on docker-entrypoint.sh
> +#gateway=$(/sbin/ip route|awk '/default/ { print $3 }')	# sometimes there is no /sbin/ip ...
Group like variables please (move down a line or the other gateway up a line)

2016-09-28 12:30 UTC, sjug commented on docker-entrypoint.sh
> +{
Oh man Jiri, your next line curl braces make my eyes bleed. :eyes:

2016-09-28 12:30 UTC, sjug commented on docker-entrypoint.sh
> +  if test "${server}" = "127.0.0.1" || test "${server}" = "" ; then
[[ ... ]] is preferred

2016-09-28 12:30 UTC, sjug commented on docker-entrypoint.sh
> +  have_server "${GUN}"
Is it better to have these one line functions or just to have a case statement that sets ${server} based on the $1 arg?

2016-09-28 12:30 UTC, sjug commented on docker-entrypoint.sh
> +  do
'do' should be on same like as while, but I do see why you've done it with your next line curly brace style :smile:

2016-09-28 12:30 UTC, sjug commented on docker-entrypoint.sh
> +  local err="${1:-$?}"
I like the use of local vars

2016-09-28 12:30 UTC, sjug commented on docker-entrypoint.sh
> +      [ "${ROUTER_IP}" ] && echo "${ROUTER_IP} ${TARGET_HOST}" >> /etc/hosts
[[ ... ]] preferred please. "The conditional expression is meant as the modern variant of the classic test command."

2016-09-28 12:30 UTC, sjug commented on docker-entrypoint.sh
> +        -j "${results_filename}".log -Jgun="${GUN}" || die $? "${RUN} failed: $?"
Nice failure trap there

2016-09-28 12:30 UTC, sjug commented on docker-entrypoint.sh
> +      have_pbench && scp -p *.jtl *.log *.png ${PBENCH_HOST}:${PBENCH_DIR}
Not sure how I feel about this without a conditional. It should work but... Feels wrong?

2016-09-28 12:50 UTC, jmencak commented on Dockerfile
> +RUN curl -Ls https://raw.githubusercontent.com/jmencak/perf-tools/master/slstress_go/logger.sh > \
Will try to change.

2016-09-28 12:50 UTC, jmencak commented on docker-entrypoint.sh
> +#gateway=$(/sbin/ip route|awk '/default/ { print $3 }')	# sometimes there is no /sbin/ip ...
Agreed.

2016-09-28 12:50 UTC, jmencak commented on docker-entrypoint.sh
> +gateway=$(printf "%d.%d.%d.%d" 0x${gw_hex:6:2} 0x${gw_hex:4:2} 0x${gw_hex:2:2} 0x${gw_hex:0:2})
Any system without "bc".  How do you do this better?

2016-09-28 12:50 UTC, jmencak commented on docker-entrypoint.sh
> +{
Probably everyone's Golang fans do...

2016-09-28 12:50 UTC, jmencak commented on docker-entrypoint.sh
> +  if test "${server}" = "127.0.0.1" || test "${server}" = "" ; then
[[ doesn't work with shells like original Bourne shell, dash, ... and it is by some considered by some bad practise

2016-09-28 12:50 UTC, jmencak commented on docker-entrypoint.sh
> +  have_server "${GUN}"
Probably unneeded functions, will just use have_server then.

2016-09-28 12:50 UTC, jmencak commented on docker-entrypoint.sh
> +      [ "${ROUTER_IP}" ] && echo "${ROUTER_IP} ${TARGET_HOST}" >> /etc/hosts
[[ introduces compatibility issues when moving/porting to other shells

2016-09-28 12:51 UTC, jmencak commented on docker-entrypoint.sh
> +      have_pbench && scp -p *.jtl *.log *.png ${PBENCH_HOST}:${PBENCH_DIR}
Does, work.  Feels right :-)

2016-09-28 12:53 UTC, jmencak commented
The issue I've noticed in the original is errors being reporting to STDOUT.

2016-09-28 12:54 UTC, sjug commented on docker-entrypoint.sh
> +gateway=$(printf "%d.%d.%d.%d" 0x${gw_hex:6:2} 0x${gw_hex:4:2} 0x${gw_hex:2:2} 0x${gw_hex:0:2})
I don't know I don't have these problems, lol.. Not saying you can do anything about it, it's just ugly.

2016-09-28 12:55 UTC, sjug commented on docker-entrypoint.sh
> +  if test "${server}" = "127.0.0.1" || test "${server}" = "" ; then
Are we using any non-bash shells? Also lots of people think voting Trump is a good idea, doesn't make them right.

2016-09-28 14:13 UTC, jmencak commented on Dockerfile
> +RUN curl -Ls https://raw.githubusercontent.com/jmencak/perf-tools/master/slstress_go/logger.sh > \
See #a621d34

2016-09-28 14:57 UTC, jmencak commented on docker-entrypoint.sh
> +  do
Addressed in    dd55e19.

2016-09-28 14:58 UTC, jmencak commented on docker-entrypoint.sh
> +  have_server "${GUN}"
Addressed in dd55e19.

2016-09-28 15:32 UTC, sjug approved these changes
Looks so much better, thanks @jmencak

2016-09-28 15:33 UTC, merged